resources:
- ./../../../../../../apps/moonshot-sample/v1
- input-configmap.yaml
- process-configmap.yaml
- output-configmap.yaml
- output-connection-string-sealedsecret.yaml
- namespace.yaml

namespace: moonshot-sample

configMapGenerator:
- name: input-configuration
  behavior: merge
  files:
  - tags-configuration.yaml

patches:
- path: ./../../../../../../.defaults/portland-properties-configmap-1.0.yaml
  target:
    name: input-configuration
    kind: ConfigMap
# - patch: |-
#     - op: replace
#       path: /data/plant.name
#       value: portland-dev
  target:
    name: input-configuration
    kind: ConfigMap
