resources:
- ./../../../../../../apps/dummy-app/v1
- namespace.yaml

namespace: dummy-app

configMapGenerator:
- name: configuration-ipaddresses
  behavior: replace
  files:
  - ipaddresses.config.json
