resources:
- ./../../../../../../apps/moonshot-sample/v1
- input-configmap.yaml
- process-configmap.yaml
- output-configmap.yaml
- output-connection-string-sealedsecret.yaml
- namespace.yaml

namespace: moonshot-sample


configMapGenerator:
- name: input-configuration
  behavior: merge
  files:
  - tags=tags-configuration.yaml
