apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: output-connection-string
  namespace: default
spec:
  encryptedData:
    connection-string: AgBI81ib8dHCTsQlhC0WCaOr61idNtMOzZV9ZpX87IrwAlhSBOAyHaove4PD8qTDZ2k2mXIn7E/jbbDaoIUs/AeaNJXa01AwtCxptZen6mZBMtcTy2nkOrGt1wdn/Pz6Eks9gdN2nPh8ZMauYevPQ96BE7FmypdmvUN/Dt/i/5jTGifRYht5jqUL8TsFbfzx8tj2cCS0LilIMawzsJ4P1vRcNf8jzRxYjLjaykLQaBx5cxdOI2lpTsubAgLG3BP7oktuo6cQ03yBeZ3B3xGxol1/pr5KWMpEVCTICGNNKzgAmS9FBTih+Q/kRuXmaWKWhTofK9rcreNwRNL1MrgJ7XDjYc1U/0SkRAcSOSLi1jx002XI49EcSHT14HTIsBxhcbKj9o3zSm0jibcNuBjpnx99tCpspmAW2cb0S3PDD83nzHWTHJ+qS32tI5QRKRm5DDpNV3UpUw2mjhIBt/ETt260Yf5RNEvE6DsD9WmIVsB6EG3p7Wm0KXmC82UtHkXO5W1w9Sv5rgYoL2fz11+MwmlR/qMiJ4vwEONmtnfqXqyvTCJb4SDkQpHZSOdWWWS3yQjN4pBK4/5l5lJ0LuwTtP/SIHJtb4KnMQCRFwo7BPnLZER1PQtJOCmkDmO5aDfRXtz1qjoFA//oeZHpNfjuOVmQN9IvciB0nsrRm/VJhrjv6gkyncCiC98TxnmJYSsWqGO4WQf5mbRr55D5Q7GSACcMX6Vd6zR8Xak=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: output-connection-string
      namespace: default

